In [9]:
 #	문제	21
 #	'22년	1분기	매출액을	구하시오
#	(매출액	=	판매수*개당수익)
import pandas as pd
df = pd.DataFrame( {
    '날짜': ['20220103','20220105', '20230105','20230127','20220203', '20220205','20230210','20230223','20230312','20230422','20220505','20230511'],
    '제품' : ['A','B', 'A', 'B', 'A', 'B','A', 'B', 'A', 'B', 'A', 'A'],
    '판매수': [3, 5, 5, 10, 10, 10, 15, 15, 20, 25, 30, 40], 
    '개당수익': [300, 400, 500, 600, 400, 500, 500, 600, 600, 700, 600, 600] })

df['날짜'] = pd.to_datetime(df['날짜'])
df['year'] = df['날짜'].dt.year
df['month'] = df['날짜'].dt.month
df['day'] = df['날짜'].dt.day

df['매출액'] = df['판매수']*df['개당수익']

cond1 = (df['year']==2022)
cond2 = (df['month']<=3)

print(df['매출액'][cond1 & cond2].sum())

11900

In [19]:
# 강의 풀이 1
df = pd.DataFrame( {
    '날짜': ['20220103','20220105', '20230105','20230127','20220203', '20220205','20230210','20230223','20230312','20230422','20220505','20230511'],
    '제품' : ['A','B', 'A', 'B', 'A', 'B','A', 'B', 'A', 'B', 'A', 'A'],
    '판매수': [3, 5, 5, 10, 10, 10, 15, 15, 20, 25, 30, 40], 
    '개당수익': [300, 400, 500, 600, 400, 500, 500, 600, 600, 700, 600, 600] })
df['날짜'] = pd.to_datetime(df['날짜'])
df['year'] = df['날짜'].dt.year
df['month'] = df['날짜'].dt.month
df['day'] = df['날짜'].dt.day

df['매출액'] = df['판매수']*df['개당수익']

df = df[df['year']==2022]

m1 = df['매출액'][df['month']==1].sum()
m2 = df['매출액'][df['month']==2].sum()
m3 = df['매출액'][df['month']==3].sum()

print(m1+m2+m3)

11900

In [20]:
# 강의 풀이 2
df = pd.DataFrame( {
    '날짜': ['20220103','20220105', '20230105','20230127','20220203', '20220205','20230210','20230223','20230312','20230422','20220505','20230511'],
    '제품' : ['A','B', 'A', 'B', 'A', 'B','A', 'B', 'A', 'B', 'A', 'A'],
    '판매수': [3, 5, 5, 10, 10, 10, 15, 15, 20, 25, 30, 40], 
    '개당수익': [300, 400, 500, 600, 400, 500, 500, 600, 600, 700, 600, 600] })

df['날짜'] = pd.to_datetime(df['날짜'])

df['매출액'] = df['판매수']*df['개당수익']

df_after = df[df['날짜'].between('2022-01-01','2022-03-31')]

print(df_after['매출액'].sum())

11900

In [23]:
# 강의 풀이 3
df = pd.DataFrame( {
    '날짜': ['20220103','20220105', '20230105','20230127','20220203', '20220205','20230210','20230223','20230312','20230422','20220505','20230511'],
    '제품' : ['A','B', 'A', 'B', 'A', 'B','A', 'B', 'A', 'B', 'A', 'A'],
    '판매수': [3, 5, 5, 10, 10, 10, 15, 15, 20, 25, 30, 40], 
    '개당수익': [300, 400, 500, 600, 400, 500, 500, 600, 600, 700, 600, 600] })

df['날짜'] = pd.to_datetime(df['날짜'])

df['매출액'] = df['판매수']*df['개당수익']

df = df.set_index('날짜')
df_after = df.loc[(df.index>='2022-01-01')&(df.index<='2022-03-31')]
print(df_after['매출액'].sum())

11900

In [29]:
 #	문제	22
 #	'22년과	'23년의	총	매출액	차이를	절대값으로	구하시오.	
#	(매출액	=	판매수*개당수익)
df = pd.DataFrame( {
    '날짜': ['20220103','20220105', '20230105','20230127','20220203', '20220205','20230210','20230223','20230312','20230422','20220505','20230511'],
    '제품' : ['A','B', 'A', 'B', 'A', 'B','A', 'B', 'A', 'B', 'A', 'A'],
    '판매수': [3, 5, 5, 10, 10, 10, 15, 15, 20, 25, 30, 40], 
    '개당수익': [300, 400, 500, 600, 400, 500, 500, 600, 600, 700, 600, 600] })

df['날짜'] = pd.to_datetime(df['날짜'])

df['매출액'] = df['판매수']*df['개당수익']

df['year'] = df['날짜'].dt.year

df_2022 = df[df['year']==2022]
df_2023 = df[df['year']==2023]

m2022 = df_2022['매출액'].sum()
m2023 = df_2023['매출액'].sum()

print(abs(m2022-m2023))

48600

In [31]:
# 다른 풀이
df = pd.DataFrame( {
    '날짜': ['20220103','20220105', '20230105','20230127','20220203', '20220205','20230210','20230223','20230312','20230422','20220505','20230511'],
    '제품' : ['A','B', 'A', 'B', 'A', 'B','A', 'B', 'A', 'B', 'A', 'A'],
    '판매수': [3, 5, 5, 10, 10, 10, 15, 15, 20, 25, 30, 40], 
    '개당수익': [300, 400, 500, 600, 400, 500, 500, 600, 600, 700, 600, 600] })

df['매출액'] = df['판매수']*df['개당수익']

df_2022 = df[df['날짜'].str.contains('2022')]
df_2023 = df[df['날짜'].str.contains('2023')]

m2022 = df_2022['매출액'].sum()
m2023 = df_2023['매출액'].sum()

print(abs(m2022-m2023))

48600

In [40]:
 #	문제	23
 #	'23년	총	매출액이	큰	제품의	23년	판매수를	구하시오.
 #	(매출액	=	판매수*개당수익)
df = pd.DataFrame( {
    '날짜': ['20220103','20220105', '20230105','20230127','20220203', '20220205','20230210','20230223','20230312','20230422','20220505','20230511'],
    '제품' : ['A','B', 'A', 'B', 'A', 'B','A', 'B', 'A', 'B', 'A', 'A'],
    '판매수': [3, 5, 5, 10, 10, 10, 15, 15, 20, 25, 30, 40], 
    '개당수익': [300, 400, 500, 600, 400, 500, 500, 600, 600, 700, 600, 600] })

df['매출액'] = df['판매수']*df['개당수익']

df_2023 = df[df['날짜'].str.contains('2023')]

df_2023_sort = df_2023.sort_values('매출액', ascending=False)
print(df_2023_sort.iloc[0])
# 제품 A의 판매수
A = df[df['제품']=='A']
A_2023 = A[A['날짜'].str.contains('2023')]
print(A_2023['판매수'].sum())

날짜      20230511
제품             A
판매수           40
개당수익         600
매출액        24000
Name: 11, dtype: object
80

In [47]:
# 강의 풀이
# 정답은 맞았지만 완전 잘못 이해함.
# A와 B를 비교했었어야 함.
#	'23년	총	매출액이	큰	제품의	23년	판매수를	구하시오.
#	(매출액	=	판매수*개당수익)
df = pd.DataFrame( {
    '날짜': ['20220103','20220105', '20230105','20230127','20220203', '20220205','20230210','20230223','20230312','20230422','20220505','20230511'],
    '제품' : ['A','B', 'A', 'B', 'A', 'B','A', 'B', 'A', 'B', 'A', 'A'],
    '판매수': [3, 5, 5, 10, 10, 10, 15, 15, 20, 25, 30, 40], 
    '개당수익': [300, 400, 500, 600, 400, 500, 500, 600, 600, 700, 600, 600] })

df['날짜'] = pd.to_datetime(df['날짜'])

df['매출액'] = df['판매수']*df['개당수익']

df['year'] = df['날짜'].dt.year

df = df[df['year']==2023]

df_a = df[df['제품']=='A']
df_b = df[df['제품']=='B']

print(df_a['매출액'].sum(), df_b['매출액'].sum())
# A가 더 큼.
print(df_a['판매수'].sum())

46000 32500
80

In [54]:
#	문제	24
 #	매출액이	4천원	초과,	1만원	미만인	데이터	수를	출력하시오.	
#	(매출액	=	판매수*개당수익)
df = pd.DataFrame( {
    '날짜': ['20220103','20220105', '20230105','20230127','20220203', '20220205','20230210','20230223','20230312','20230422','20220505','20230511'],
    '제품' : ['A','B', 'A', 'B', 'A', 'B','A', 'B', 'A', 'B', 'A', 'A'],
    '판매수': [3, 5, 5, 10, 10, 10, 15, 15, 20, 25, 30, 40], 
    '개당수익': [300, 400, 500, 600, 400, 500, 500, 600, 600, 700, 600, 600] })

df['매출액'] = df['판매수']*df['개당수익']

cond1 = (df['매출액']>4000)
cond2 = (df['매출액']<10000)

print(len(df[cond1&cond2]))

4